spring:
  application:
    name: loginms

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource: 
    username: sa
    password: 
    url: jdbc:h2:mem:userDb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  zipkin:
    enabled: true
    base-url: ${zipkin.url:http://192.168.99.102:9411}
  sleuth:
    trace-id128: true
    enabled: true
    sampler:
      probability: 1.0 
jwt:
  secret: secretkey
  get:
    token:
      uri: /authenticate
      
jwt.token.validity.minuite: 30

server:
  port: 8081  
  
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: ${eureka.uri:http://192.168.99.102:8761/eureka}     