spring:
  application:
    name: cartms
  rabbitmq:
    host: ${rabbitmq.host:192.168.99.102}
    port: ${rabbitmq.port:5672}
  cloud:
    bus:
      destination: configXchangebus
      enabled: true  
    stream:
      bindings:
        webaudit-out:
          destination: webaudit
          group: audit
    

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        
  datasource: 
    username: sa
    password: 
    url: jdbc:h2:mem:cartDb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  security:
    basic:
      enabled: false
    user:
      name: admin
      password: admin


server:
  port: 8084
  
management:
  endpoints:
    web:
      exposure:
        include: '*'  
        
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka.uri:http://192.168.99.102:8761/eureka}
      
feign:
  hystrix:
    enabled: true