spring:
  application:
    name: productms
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true        
  datasource: 
    username: sa
    password: 
    url: jdbc:h2:mem:productDb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  security:
    basic:
      enabled: false    user:      name: admin
      password: admin
  zipkin:
    enabled: true
    base-url: ${zipkin.url:http://192.168.99.102:9411}
  sleuth:
    trace-id128: true
    enabled: true
    sampler:
      probability: 1.0     


server:
  port: 8083
  
management:
  endpoints:
    web:
      exposure:
        include: '*'  
        
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka.uri:http://192.168.99.102:8761/eureka}
      
feign:
  hystrix:
    enabled: true
    
